site_name: RoE Card Docs
theme: 
  name: material
  features: 
    - navigation.tabs
    - navigation.section
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette: 
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
      primary: red
      accent: red
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to Dark Mode
      primary: red
      accent: red

copyright: |
  Copyright &copy; 2024 Trident Task Force, All rights reserved